// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx6rFOTpIcXy9DYXh9FngwuqYUHwsH4Ck',
    appId: '1:263657368069:web:b0ff07e8713dbf9d590a6c',
    messagingSenderId: '263657368069',
    projectId: 'clasemoviles-fb6dc',
    authDomain: 'clasemoviles-fb6dc.firebaseapp.com',
    storageBucket: 'clasemoviles-fb6dc.firebasestorage.app',
    measurementId: 'G-Z0ZJRZSGKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIsbLNZho8rsxCxkJuaY3fcKGBvnc8jmo',
    appId: '1:263657368069:android:2b7275ea4b47ad57590a6c',
    messagingSenderId: '263657368069',
    projectId: 'clasemoviles-fb6dc',
    storageBucket: 'clasemoviles-fb6dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzA6ANgm5RSmQydPYiCkj46o44BLZHfX8',
    appId: '1:263657368069:ios:0db6faf630837f7e590a6c',
    messagingSenderId: '263657368069',
    projectId: 'clasemoviles-fb6dc',
    storageBucket: 'clasemoviles-fb6dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzA6ANgm5RSmQydPYiCkj46o44BLZHfX8',
    appId: '1:263657368069:ios:0db6faf630837f7e590a6c',
    messagingSenderId: '263657368069',
    projectId: 'clasemoviles-fb6dc',
    storageBucket: 'clasemoviles-fb6dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx6rFOTpIcXy9DYXh9FngwuqYUHwsH4Ck',
    appId: '1:263657368069:web:6e370f83201a4405590a6c',
    messagingSenderId: '263657368069',
    projectId: 'clasemoviles-fb6dc',
    authDomain: 'clasemoviles-fb6dc.firebaseapp.com',
    storageBucket: 'clasemoviles-fb6dc.firebasestorage.app',
    measurementId: 'G-K94LLBDL6J',
  );
}
